esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp32:
  board: esp32-poe-iso
  framework:
    type: esp-idf

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0
  power_pin: GPIO12
  
i2c:
  sda: GPIO13
  scl: GPIO16

<<: !include ../lib/base.yaml